Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# Bag of words

In [ ]:
# importing libraries

import numpy as np
import pandas as pd

In [ ]:
# preparing dataset

df = pd.DataFrame({"text":["people learning generativeai",
                         "generativeai datascience generativeai",
                         "people write blogs",
                          "datascience with generativeai"],"output":[1,1,0,0]})

df

text  output
0           people learning generativeai       1
1  generativeai datascience generativeai       1
2                     people write blogs       0
3          datascience with generativeai       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer    # To get the frequency of words

cv = CountVectorizer()

In [ ]:
# getting the frequency of each word from dataset

bow = cv.fit_transform(df['text'])

In [ ]:
# vocabulary  -> getting unique words

print(cv.vocabulary_)

{'people': 4, 'learning': 3, 'generativeai': 2, 'datascience': 1, 'write': 6, 'blogs': 0, 'with': 5}


In [ ]:
# Getting the array form of words refering index from vocabulary

print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 1 1 0 0]]
[[0 1 2 0 0 0 0]]
[[1 0 0 0 1 0 1]]


In [ ]:
# new

cv.transform(['learning generativeai']).toarray()

array([[0, 0, 1, 1, 0, 0, 0]])

In [ ]:
X = bow.toarray()
y = df['output']

#  N-grams
We can define number of representation

In [ ]:
df = pd.DataFrame({"text":["people learning generativeai",
                         "generativeai datascience generativeai",
                         "people write blogs",
                          "datascience with generativeai"],"output":[1,1,0,0]})

df

text  output
0           people learning generativeai       1
1  generativeai datascience generativeai       1
2                     people write blogs       0
3          datascience with generativeai       0

In [ ]:
# 2 words representation

# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people learning': 4, 'learning generativeai': 3, 'generativeai datascience': 2, 'datascience generativeai': 0, 'people write': 5, 'write blogs': 7, 'datascience with': 1, 'with generativeai': 6}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 1 1 0 0 0]]
[[1 0 1 0 0 0 0 0]]
[[0 0 0 0 0 1 0 1]]


In [ ]:
# 3 words representation

#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people learning generativeai': 2, 'generativeai datascience generativeai': 1, 'people write blogs': 3, 'datascience with generativeai': 0}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[0 1 0 0]]
[[0 0 0 1]]


# TF-IDF (Term frequency- Inverse document frequency)

In [ ]:
df = pd.DataFrame({"text":["people learning generativeai",
                         "generativeai datascience generativeai",
                         "people write blogs",
                          "datascience with generativeai"],"output":[1,1,0,0]})

df

text  output
0           people learning generativeai       1
1  generativeai datascience generativeai       1
2                     people write blogs       0
3          datascience with generativeai       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [ ]:
# getting the weights of words

tfid.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.44809973, 0.70203482, 0.55349232,
        0.        , 0.        ],
       [0.        , 0.52546357, 0.8508161 , 0.        , 0.        ,
        0.        , 0.        ],
       [0.61761437, 0.        , 0.        , 0.        , 0.48693426,
        0.        , 0.61761437],
       [0.        , 0.55349232, 0.44809973, 0.        , 0.        ,
        0.70203482, 0.        ]])

In [ ]:
# Idf number

print(tfid.idf_)

[1.91629073 1.51082562 1.22314355 1.91629073 1.51082562 1.91629073
 1.91629073]
